name: Deploy Laravel Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Sync application files (with protection for user uploads)
      uses: easingthemes/ssh-deploy@v5.0.0
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
        SOURCE: "./"
        TARGET: "public_html/tuan-coffee"
        # DITAMBAHKAN: Melindungi folder tempat file unggahan disimpan
        EXCLUDE: "/.git/, /node_modules/, /vendor/, /storage/app/public/"

    - name: Run setup commands on server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.REMOTE_PORT }}
        script: |
          cd public_html/tuan-coffee
          
          # 1. Setup .env file
          cp .env.example .env
          sed -i "s|APP_URL=http://localhost|APP_URL=${{ secrets.APP_URL }}|g" .env
          sed -i "s|DB_DATABASE=laravel|DB_DATABASE=${{ secrets.DB_DATABASE }}|g" .env
          sed -i "s|DB_USERNAME=root|DB_USERNAME=${{ secrets.DB_USERNAME }}|g" .env
          sed -i "s|DB_PASSWORD=|DB_PASSWORD=${{ secrets.DB_PASSWORD }}|g" .env
          
          # 2. Run Laravel installation and optimization
          composer install --no-interaction --no-dev --optimize-autoloader
          php artisan key:generate
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          php artisan migrate:fresh --seed
          
          # 3. Create storage link manually
          if [ -L "public/storage" ]; then
              rm "public/storage"
          fi
          ln -s $PWD/storage/app/public $PWD/public/storage
          
          echo "🚀 Deployment Laravel selesai!"
